import Head from "next/head";
import { dehydrate } from "@tanstack/react-query";
import { fetchJobs, queryClient } from "../server/api";
import Header from "../components/Header";
import Jobs from "../components/Jobs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jobbatical</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Jobs />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  await queryClient.prefetchQuery(["jobs"], async () => await fetchJobs());

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
